date = {
    'nodes': [
        {'preQueryNodes': None, 'args': [('Url', 12), ('kwargs', 13)], 'returns': (('Doc', 0), ('Result', 1)),
         'eventLinks': {'Out': [(2, 'ConsoleOutput'), (3, 'ContainerGetItem')]}, 'preLinks': {'In': True},
         'returns_linked': True},
        {'preQueryNodes': None, 'args': [], 'returns': (), 'eventLinks': {'Out': [(0, 'PyQueryUrl')]},
         'preLinks': {}},
        {'preQueryNodes': None, 'args': [('Doc', 0)], 'returns': (), 'eventLinks': {},
         'preLinks': {'In': True}},
        {'preQueryNodes': None, 'args': [('doc_in', 1), ('field', 14)], 'returns': (('doc_out', 2),),
         'eventLinks': {'Out': [(4, 'IteratorList')]}, 'preLinks': {'In': True}, 'returns_linked': True},
        {'preQueryNodes': None, 'args': [('doc_in', 2)], 'returns': (('doc', 3),),
         'eventLinks': {'Out': [(5, 'StringConcat')]}, 'preLinks': {'In': True}, 'returns_linked': True},
        {'preQueryNodes': None, 'args': [('prefix', 15), ('suffix', 3)], 'returns': (('result', 4),),
         'eventLinks': {'Out': [(6, 'PyQueryUrl')]}, 'preLinks': {'In': True}, 'returns_linked': True},
        {'preQueryNodes': None, 'args': [('Url', 4), ('kwargs', 16)], 'returns': (('Doc', 5), ('Result', 6)),
         'eventLinks': {'Out': [(7, 'ContainerGetItem')]}, 'preLinks': {'In': True}, 'returns_linked': True},
        {'preQueryNodes': None, 'args': [('doc_in', 6), ('field', 17)], 'returns': (('doc_out', 7),),
         'eventLinks': {'Out': [(8, 'IteratorList')]}, 'preLinks': {'In': True}, 'returns_linked': True},
        {'preQueryNodes': None, 'args': [('doc_in', 7)], 'returns': (('doc', 8),),
         'eventLinks': {'Out': [(9, 'PyQueryUrl'), (10, 'ConsoleOutput')]}, 'preLinks': {'In': True},
         'returns_linked': True},
        {'preQueryNodes': None, 'args': [('Url', 8), ('kwargs', 18)], 'returns': (('Doc', 9), ('Result', 10)),
         'eventLinks': {'Out': [(11, 'FieldMakeup')]}, 'preLinks': {'In': True}, 'returns_linked': True},
        {'preQueryNodes': None, 'args': [('Doc', 8)], 'returns': (), 'eventLinks': {},
         'preLinks': {'In': True}},
        {'preQueryNodes': None, 'args': [('doc_in', 9), ('kwargs', 19)], 'returns': (('doc_out', 11),),
         'eventLinks': {'Out': [(12, 'ConsoleOutput')]}, 'preLinks': {'In': True}, 'returns_linked': True},
        {'preQueryNodes': None, 'args': [('Doc', 11)], 'returns': (), 'eventLinks': {},
         'preLinks': {'In': True}}],
    'runTimeData': [None, None, None, None, None, None, None, None, None, None, None, None, 'www',
                    {'departments': ['.clearfix > li > a', True, 'href']}, 'departments', 'www',
                    {'doctors': ['.ks_yishi > ul > li > a', True, 'href']}, 'doctors',
                    {'name': ['#showexpdiv > ul > li.zj_xm > strong', False, None]},
                    {'hospital': '北京301医院', 'grade': '三甲'}],
    'clientEventListeners': {},
    'levelEventListeners': {'on_script_start': [], 'on_player_load_scene_finish': [], 'on_player_unit_dead': []},
    'taskEventListeners': {}, 'activityStartListeners': {}, 'levelTimesUseoutEventListeners': {},
    'openPublicInstnaceEventListeners': {},
    'questionEventListeners': [],
    'staticMechanisms': []
}
